Repository f-lab-edu/IT-Hermes-Server, pull requests merged in 2023-01, with the labels that each got.

#12 Feat: 프로젝트 엔티티 추가
  src/main/java/com/hermes/ithermes/ItHermesApplication.java
  src/main/java/com/hermes/ithermes/domain/entity/Alarm.java
  src/main/java/com/hermes/ithermes/domain/entity/BaseEntity.java
  src/main/java/com/hermes/ithermes/domain/entity/Category.java
  src/main/java/com/hermes/ithermes/domain/entity/CrawlingContents.java
  src/main/java/com/hermes/ithermes/domain/entity/CrawlingContentsRegistry.java
  src/main/java/com/hermes/ithermes/domain/entity/Keyword.java
  src/main/java/com/hermes/ithermes/domain/entity/Service.java
  src/main/java/com/hermes/ithermes/domain/entity/User.java
  src/main/java/com/hermes/ithermes/domain/entity/UserRegistry.java
Labels: ✨Feat

#22 Fix : (긴급반영) Alarm, Service 네이밍 리펙토링
  src/main/java/com/hermes/ithermes/application/AlarmService.java
  src/main/java/com/hermes/ithermes/application/SubscribeService.java
  src/main/java/com/hermes/ithermes/domain/entity/ContentsProvider.java
  src/main/java/com/hermes/ithermes/domain/entity/Job.java
  src/main/java/com/hermes/ithermes/domain/entity/Subscribe.java
  src/main/java/com/hermes/ithermes/domain/entity/YoutubeAndNews.java
  src/main/java/com/hermes/ithermes/domain/factory/AlarmFactory.java
  src/main/java/com/hermes/ithermes/domain/factory/ParseAlarmFunctionalFactory.java
  src/main/java/com/hermes/ithermes/domain/factory/ParseSubscribeFunctionalFactory.java
  src/main/java/com/hermes/ithermes/domain/factory/SubscribeFactory.java
  src/main/java/com/hermes/ithermes/domain/util/CategoryType.java
  src/main/java/com/hermes/ithermes/domain/util/ContentsProviderType.java
  src/main/java/com/hermes/ithermes/infrastructure/AlarmRepository.java
  src/main/java/com/hermes/ithermes/infrastructure/ContentsProviderRepository.java
  src/main/java/com/hermes/ithermes/infrastructure/ServiceRepository.java
  src/main/java/com/hermes/ithermes/infrastructure/SubscribeRepository.java
  src/main/java/com/hermes/ithermes/presentation/controller/AlarmController.java
  src/main/java/com/hermes/ithermes/presentation/controller/SubscribeController.java
  src/main/java/com/hermes/ithermes/presentation/dto/subscribe/SubscribeFindSubscribeRequestDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/subscribe/SubscribeFindSubscribeResponseDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/subscribe/SubscribePutSubscribeRequestDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/subscribe/SubscribeResponseDto.java
  src/main/resources/data.sql
  src/test/java/com/hermes/ithermes/application/UserServiceTest.java
Labels: 🐞 bug & fix

#13 Feat : 조회수 순으로 TOP10글 조회, 카테고리별 글 조회 api 구현
  src/main/java/com/hermes/ithermes/ItHermesApplication.java
  src/main/java/com/hermes/ithermes/application/ContentsService.java
  src/main/java/com/hermes/ithermes/domain/entity/ContentsEntityInterface.java
  src/main/java/com/hermes/ithermes/domain/entity/Job.java
  src/main/java/com/hermes/ithermes/domain/entity/User.java
  src/main/java/com/hermes/ithermes/domain/entity/YoutubeAndNews.java
  src/main/java/com/hermes/ithermes/domain/exception/NotExistsRequestParamException.java
  src/main/java/com/hermes/ithermes/domain/util/CategoryType.java
  src/main/java/com/hermes/ithermes/domain/util/OrderType.java
  src/main/java/com/hermes/ithermes/infrastructure/JobRepository.java
  src/main/java/com/hermes/ithermes/infrastructure/ServiceRepository.java
  src/main/java/com/hermes/ithermes/infrastructure/YoutubeAndNewsRepository.java
  src/main/java/com/hermes/ithermes/presentation/GlobalExceptionHandler.java
  src/main/java/com/hermes/ithermes/presentation/controller/ContentsController.java
  src/main/java/com/hermes/ithermes/presentation/controller/CrawlingController.java
  src/main/java/com/hermes/ithermes/presentation/dto/contents/ContentsContentsDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/contents/ContentsDtoInterface.java
  src/main/java/com/hermes/ithermes/presentation/dto/contents/MainPageContentsContentsDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/crawling/CrawlingResponseDto.java
  src/test/java/com/hermes/ithermes/application/ContentsServiceTest.java
  src/test/java/com/hermes/ithermes/presentation/ContentsControllerTest.java
Labels: ✨Feat

#23 Refactor : 회원,구독 리펙토링
  src/main/java/com/hermes/ithermes/application/UserService.java
  src/main/java/com/hermes/ithermes/domain/factory/ContentsProviderFactory.java
  src/main/java/com/hermes/ithermes/domain/factory/SubscribeFactory.java
  src/main/java/com/hermes/ithermes/domain/factory/UserFactory.java
  src/main/java/com/hermes/ithermes/domain/functional/ParseSubscribeFunctional.java
  src/main/java/com/hermes/ithermes/domain/util/CategoryType.java
  src/main/java/com/hermes/ithermes/domain/util/JobType.java
  src/main/java/com/hermes/ithermes/presentation/GlobalExceptionHandler.java
  src/main/java/com/hermes/ithermes/presentation/dto/subscribe/SubscribePutSubscribeRequestDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/user/UserCreateUserRequestDto.java
Labels: ⚒️ Refactor

#37 Feat : Insert 구현(사람인, 요즘IT, 드림코딩엘리)
  src/main/java/com/hermes/ithermes/ItHermesApplication.java
  src/main/java/com/hermes/ithermes/application/JobService.java
  src/main/java/com/hermes/ithermes/application/YoutubeAndNewsService.java
  src/main/java/com/hermes/ithermes/domain/entity/Job.java
  src/main/java/com/hermes/ithermes/domain/entity/YoutubeAndNews.java
  src/main/java/com/hermes/ithermes/domain/factory/JobFactory.java
  src/main/java/com/hermes/ithermes/domain/factory/YoutubeAndNewsFactory.java
  src/main/java/com/hermes/ithermes/domain/util/CategoryType.java
  src/main/java/com/hermes/ithermes/domain/util/ContentsProviderType.java
  src/main/java/com/hermes/ithermes/domain/util/GradeType.java
  src/main/java/com/hermes/ithermes/domain/util/JobType.java
  src/main/java/com/hermes/ithermes/infrastructure/JobJpaRepository.java
  src/main/java/com/hermes/ithermes/infrastructure/YoutubeAndNewsJpaRepository.java
  src/main/java/com/hermes/ithermes/presentation/controller/JobController.java
  src/main/java/com/hermes/ithermes/presentation/controller/YoutubeAndNewsController.java
  src/main/java/com/hermes/ithermes/presentation/dto/job/JobCrawlingDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/job/JobInsertRequestDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/job/JobLastUrlRequestDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/job/JobLastUrlResponseDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/youtubeandnews/YoutubeAndNewsCrawlingDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/youtubeandnews/YoutubeAndNewsInsertDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/youtubeandnews/YoutubeAndNewsLastUrlRequestDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/youtubeandnews/YoutubeAndNewsLastUrlResponseDto.java
Labels: ✨Feat

#48 Feat: lastUrl로직 추가, 추천정보 알림기능 구현
  src/main/java/com/hermes/ithermes/application/AlarmService.java
  src/main/java/com/hermes/ithermes/domain/entity/Subscribe.java
  src/main/java/com/hermes/ithermes/domain/util/JobType.java
  src/main/java/com/hermes/ithermes/infrastructure/JobRepository.java
  src/main/java/com/hermes/ithermes/infrastructure/SubscribeRepository.java
  src/main/java/com/hermes/ithermes/infrastructure/UserRepository.java
  src/main/java/com/hermes/ithermes/infrastructure/YoutubeAndNewsRepository.java
  src/main/java/com/hermes/ithermes/presentation/controller/AlarmController.java
  src/main/java/com/hermes/ithermes/presentation/dto/contents/MainPageContentsDto.java
  src/main/resources/application.yml
  src/test/java/com/hermes/ithermes/application/AlarmServiceTest.java
Labels: ✨Feat

#46 Refactor: 엔티티 dto로 변환코드 리팩토링, contents부분 테스트코드 수정
  src/main/java/com/hermes/ithermes/domain/entity/ContentsEntityInterface.java
  src/main/java/com/hermes/ithermes/domain/entity/Job.java
  src/main/java/com/hermes/ithermes/domain/entity/YoutubeAndNews.java
  src/main/java/com/hermes/ithermes/presentation/dto/contents/ContentsDto.java
  src/main/java/com/hermes/ithermes/presentation/dto/contents/MainPageContentsDto.java
  src/test/java/com/hermes/ithermes/application/ContentsServiceTest.java
  src/test/java/com/hermes/ithermes/presentation/ContentsControllerTest.java
Labels: 🐞 bug & fix, ⚒️ Refactor
